allow procmacro usage in integration tests
bkchr/proc-macro-crate pull request #13
Opened 2021-09-08 17:01 UTC by SoftwareSheriff

If generating code for an integration test, avoid returning `FoundCrate::Itself` since that leads to incorrect paths. This fixes https://github.com/bkchr/proc-macro-crate/issues/10.

2021-09-09 07:55 UTC, bkchr requested changes
The general idea is nice!

However, it would not work currently. It would return `CrateNotFound` because a crate is normally not a dependency of itself.

```
        if let Some(toml::Value::Table(t)) = cargo_toml.get("package") {
            if let Some(toml::Value::String(s)) = t.get("name") {
                if s == orig_name {
                    if env::var_os("CARGO_TARGET_TMPDIR").is_some() {
                        return Ok(FoundCrate::Itself);
                    } else {
                        return Ok(FoundCrate::Name(sanitize_crate_name(orig_name));
                }
            }
        }
```

This should do it.

2021-09-09 15:12 UTC, SoftwareSheriff commented
I've added a commit to address that concern.

It appeared to work for me (see [here](https://forge.typ3.tech/charles/hesione/-/blob/use-macro-in-core/core/tests/derive.rs) and [here](https://forge.typ3.tech/charles/hesione/-/jobs/941#L118)), but I just realized that's probably because I [wasn't using the crate correctly](https://forge.typ3.tech/charles/hesione/-/commit/a8e29b872ca7b20f8862be8e8af5fea6c025b2c0). Indeed, what I had before didn't actually work after fixing that. [It works](https://forge.typ3.tech/charles/hesione/-/jobs/953#L120) after adding that commit though.

(Sidenote, I think your `.is_some()` is a typo; `CARGO_TARGET_TMPDIR` is only set for integration tests and not libraries/binaries, and for the latter it needs to return `FoundCrate::Itself` and for the former we need `FoundCrate::Name`.)

2021-09-09 20:49 UTC, bkchr approved these changes

2021-09-09 20:49 UTC, merged

2021-09-15 03:54 UTC, SoftwareSheriff commented
@bkchr any chance of doing a crates.io release with this change?

2021-09-15 09:23 UTC, bkchr commented
@SoftwareSheriff published as 1.1.0